name: Main

on:
	pull_request:
		branches:
		- main

	push:
		branches:
		- main

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
		- name: Checkout code
			uses: actions/checkout@v2

		- name: Use Node.js 20.x
			uses: actions/setup-node@v2
			with:
			node-version: '20.x'

		- name: Install dependencies
			run: npm install

		- name: Build
			run: npm run build

		- name: Lint
			run: npm run lint
			
		- name: Test
			run: npm run test

	release:
		needs: build
		runs-on: ubuntu-latest
		if: github.ref == 'refs/heads/main' && github.event_name == 'push'
		steps:
			- name: Checkout code
				uses: actions/checkout@v2

			- name: Use Node.js 20.x
				uses: actions/setup-node@v2
				with:
				node-version: '20.x'

			- name: Install dependencies
				run: npm install

			- name: Run semantic-release
				env:
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
				run: npx semantic-release
